Repository boostup-project/boostup-project, pull requests merged in 2022-12, with the labels that each got.

#5 feat: Member Entity 추가 및 Spring Boot 버전 변경
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/test/java/com/codueon/boostUp/BoostUpApplicationTests.java
Labels: 🚨 BugFix, ⛲ Feature, BE조경민

#6 feat: Suggest Entity 작성
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
Labels: ⛲ Feature, BE이규리

#7 feat: SuggestStatus 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
Labels: ⛲ Feature, BE이규리

#8 Member 도메인 엔티티 작성
  server/src/main/java/com/codueon/boostUp/domain/member/entity/AccountStatus.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberImage.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberStatus.java
  server/src/main/java/com/codueon/boostUp/domain/member/utils/OAuthConstant.java
Labels: 🚨 BugFix, ⛲ Feature, BE조경민

#9 feat: Bookmark Entity 작성 및 gitignore 추가
  server/.DS_Store
  server/.gitignore
  server/src/main/java/com/codueon/boostUp/domain/bookmark/entity/Bookmark.java
Labels: ⛲ Feature, BE이규리

#10 feat: Review Entity 작성 및 Bookmark Entity 수정
  server/src/main/java/com/codueon/boostUp/domain/bookmark/entity/Bookmark.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
Labels: ⛲ Feature, 🔨 Refactor, BE이규리

#13 feat: global exception 및 디스코드 webhook 추가
  server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
  server/src/main/java/com/codueon/boostUp/domain/member/exception/AuthException.java
  server/src/main/java/com/codueon/boostUp/global/exception/BusinessLogicException.java
  server/src/main/java/com/codueon/boostUp/global/exception/ErrorResponse.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/java/com/codueon/boostUp/global/exception/GlobalAdvice.java
  server/src/main/java/com/codueon/boostUp/global/webhook/SendErrorToDiscord.java
  server/src/main/java/com/codueon/boostUp/global/webhook/ServiceError.java
  server/src/main/java/com/codueon/boostUp/global/webhook/WebHookError.java
  server/src/main/java/com/codueon/boostUp/global/webhook/WebHookFeign.java
Labels: ⛲ Feature, BE조경민

#14 refactor: Lesson Entity 리펙토링
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/CareerImage.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#16 feat: 토큰 엔티티 추가
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Token.java
Labels: BE조경민

#15 refactor: Lesson Entity 리펙토링
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Address.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#18 feat: H2 Languages 및 Address 초기 데이터 작성
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Address.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
  server/src/main/java/com/codueon/boostUp/global/webhook/SendErrorToDiscord.java
  server/src/main/resources/db/h2/import.sql
Labels: ⛲ Feature, 🔨 Refactor, BE이규리

#19 fix: languages 엔티티 충돌 수정
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Address.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
Labels: 🚨 BugFix, BE조경민

#22 feat: member-dto 추가
  server/src/main/java/com/codueon/boostUp/domain/member/dto/FindPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/Login.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PatchMember.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostMember.java
Labels: BE조경민

#23 refactor: Login -> LoginDto 명명 변경
  server/src/main/java/com/codueon/boostUp/domain/member/dto/FindPasswordDto.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/LoginDto.java
Labels: BE조경민

#24 feat: Suggest DTO 작성
  server/.gitignore
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostPaymentUrl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/SuggestResponse.java
Labels: ⛲ Feature, BE이규리

#25 feat: reviewDto 작성
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PatchReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PostReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/ReviewResponse.java
Labels: BE조경민

#26 feat: Bookmark DTO 작성
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
Labels: ⛲ Feature, BE이규리

#28 feat: Lesson DTO 작성
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetDetailLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetMypageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostEditLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
Labels: ⛲ Feature, BE주석영

#27 refactor: memberDto 명명 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/GetMemberInfo.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/GetToken.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostFindPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostLogin.java
Labels: 🔨 Refactor, BE조경민

#29 refactor: GetSuggest DTO 이름 변경
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetSuggest.java
Labels: 🔨 Refactor, BE이규리

#30 refactor: ReviewResponse -> GetReview 명명 수정
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
Labels: BE조경민

#31 refatcor: GetDetailLesson DTO 생성자 리펙토링
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetDetailLesson.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#33 feat: 공통 DTO 작성
  server/src/main/java/com/codueon/boostUp/domain/dto/MultiResponseDto.java
  server/src/main/java/com/codueon/boostUp/domain/dto/PageInfo.java
  server/src/main/java/com/codueon/boostUp/domain/dto/SingleResponseDto.java
Labels: ⛲ Feature, BE이규리

#34 feat: Auditable 작성
  server/src/main/java/com/codueon/boostUp/global/util/Auditable.java
Labels: ⛲ Feature, BE주석영

#36 feat: memberController, AuthController 구조 작성
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
Labels: ⛲ Feature, BE조경민

#37 feat: Lesson Controller 구조 작성
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
Labels: ⛲ Feature, 👽️ API, BE주석영

#38 feat: Suggest Controller 구조 작성
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#39 feat: Bookmark Contoller 구조 작성
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
Labels: ⛲ Feature, BE조경민

#41 refactor: Lesson DTO에 검색 추가
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostSearchLesson.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#44 refactor: PostLesson 리펙토링
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#45 feat: Review Controller 작성
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/reviewController.java
Labels: 👽️ API, BE주석영

#53 feat: chatting 기능 controller - service - repository 구현중
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatMember.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetLastChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/ChatRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/RoomService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostEditLesson.java
  server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
  server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#54 feat: SuggestDbService 기본 구조 작성
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#58 feat: 북마크 기능 구현 중
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/entity/Bookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/CustomBookmarkRepository.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
Labels: BE조경민

#61 feat: postSuggest 과외 신청하기 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#63 test: postSuggest 과외 신청하기 테스트 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: BE이규리, ✅ Test

#64 feat: 북마크 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Address.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonLanguage.java
  server/src/main/java/com/codueon/boostUp/global/exception/GlobalAdvice.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#69 test: 북마크 테스팅(create/delete)
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/entity/Bookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
Labels: BE조경민

#75 feat: Member 공통 DB 서비스 작성
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
Labels: ⛲ Feature, 👽️ API, BE임재민

#78 feat: 리뷰 작성 및 상세페이지 리뷰 전체조회 구현
  server/src/main/java/com/codueon/boostUp/domain/dto/MultiResponseDto.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/reviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PostReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/CustomReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/java/com/codueon/boostUp/global/util/Auditable.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#79 feat : S3 Server 환경 구성 중
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/global/config/AwsS3Config.java
Labels: ⛲ Feature, 👽️ API, BE주석영

#82 refactor: lesson 엔티티 career String을 Integer로 변경
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#83 feat: 회원가입 기능 구현/ 보안 적용 중
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/security/config/SecurityConfig.java
  server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberCreateTest.java
Labels: ⛲ Feature, 👽️ API, BE임재민

#84 feat: Suggest Entity StartTime/EndTime 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
Labels: ⛲ Feature, BE이규리

#85 feat: review 조회/수정/삭제 임시 구현
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/reviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PatchReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/CustomReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#88 feat: getSuggest 마이페이지 조회 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetTeacherSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#89 test: getSuggest 테스트 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: BE이규리, ✅ Test

#93 test: Review 조회 테스트 코드 작성
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonAddress.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPostTest.java
Labels: 🚨 BugFix, BE조경민, ✅ Test

#97 refactor: 북마크 API 변경 + Review Dto 수정 - 1
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetAllDetailReviews.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
Labels: 🔨 Refactor, BE조경민

#98 refactor: 북마크 API 변경 + Review Dto 수정 - 2
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
Labels: 👽️ API, 🔨 Refactor, BE조경민

#99 refactor: getSuggest tabId if문 -> switch문 변경
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetTeacherSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
Labels: 🔨 Refactor, BE이규리

#101 feat: deleteSuggest 과외 신청 취소 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#102 test: bookmarkController Test 1차 완료
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/WrapBookmark.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/MyPageBookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
Labels: 🔨 Refactor, BE조경민, ✅ Test

#103 refactor: eleteSuggest 과외 신청 취소 기능 예외처리 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
Labels: 🔨 Refactor, BE이규리

#104 test: deleteSuggest 과외 신청 취소 Test 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: BE이규리, ✅ Test

#105 test: reviewController 1차 테스팅 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: 🔨 Refactor, BE조경민, ✅ Test

#106 feat: Lesson DTO 요구사항에 맞게 변경, 이미지 업로드 세팅
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetDetailLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonCurriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonDetail.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetStudentLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetTutorMypageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PatchLessonCurriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PatchLessonDetail.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PatchLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/CareerImage.java
  server/src/main/java/com/codueon/boostUp/global/config/AwsS3Config.java
  server/src/main/java/com/codueon/boostUp/global/file/AwsS3Service.java
  server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
  server/src/main/java/com/codueon/boostUp/global/file/UploadFile.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#108 초기 setting
  .github/ISSUE_TEMPLATE/Issue.md
  .github/ISSUE_TEMPLATE/daily-Log.md
  README.md
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc.js
  client/README.md
  client/atoms/index.tsx
  client/components/comp.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/api/hello.ts
  client/pages/index.tsx
  client/postcss.config.js
  client/public/favicon.ico
  client/public/fonts/SCDream1.otf
  client/public/fonts/SCDream2.otf
  client/public/fonts/SCDream3.otf
  client/public/fonts/SCDream4.otf
  client/public/fonts/SCDream5.otf
  client/public/fonts/SCDream6.otf
  client/public/fonts/SCDream7.otf
  client/public/fonts/SCDream8.otf
  client/public/fonts/SCDream9.otf
  client/public/images/logo.png
  client/public/vercel.svg
  client/styles/Home.module.css
  client/styles/globals.css
  client/tailwind.config.js
  client/tsconfig.json
  server/README.md
Labels: ⚙Setting, FE김상현, FE정하늘, FE박성훈

#109 feat: acceptSuggest 과외 수락하기 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#110 test: acceptSuggest 과외 수락하기 Test 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: BE이규리, ✅ Test

#111 refactor: lesson DTO 변경사항에 맞춰 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonDetail.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PatchLessonDetail.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonDetailEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonInfoEdit.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#113 feat: 반응형 사이즈 설정
  client/pages/index.tsx
  client/tailwind.config.js
Labels: ⚙Setting, FE박성훈

#114 feat: declineSuggest 과외 거절하기 기능 구현 및 Reason 취소 사유 엔티티 작성
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostReason.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Reason.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/ReasonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#117 test: declineSuggest 과외 거절하기 Test 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: BE이규리, ✅ Test

#122 feat: 실시간 채팅 초기 세팅 완료
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatMember.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetLastChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/ChatRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/RoomService.java
  server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
  server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPatchTest.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#125 feat: getSuggestInfo 결제 화면 조회 기능 구현 및 SuggestDbService 수정
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetSuggestInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#126 test: getSuggestInfo 결제 화면 조회 Test 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: BE이규리, ✅ Test

#127 refactor: getSuggestInfo totalCost 로직 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: 🔨 Refactor, BE이규리

#128 refactor: lessonId 추가 및 Teacher -> Tutor 변환
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetTutorSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: 🔨 Refactor, BE이규리
