Repository boostup-project/boostup-project, pull requests merged in 2023-01, with the labels that each got.

#137 feat: build명령어 설정
  client/package.json
Labels: ⚙Setting

#138 feat: FE자동배포 yml 파일 작성
  .github/workflows/deploy.yml
Labels: ⚙Setting

#140 feat: 자동배포 확인용 문구
  client/pages/index.tsx
Labels: ✅ Test

#141 feat: 자동배포 확인용 문구2
  client/pages/index.tsx
Labels: ✅ Test

#152 feat: 인증페이지 재사용컴포넌트 구현
  client/components/reuse/AuthBtn.tsx
  client/components/reuse/AuthContainer.tsx
  client/components/reuse/InputBox.tsx
  client/styles/globals.css
Labels: ⛲ Feature, FE박성훈

#153 feat:Login,signup,resetPassword페이지틀
  client/package-lock.json
  client/package.json
  client/pages/login.tsx
  client/pages/resetPassword.tsx
  client/pages/signup.tsx
Labels: ⛲ Feature, FE정하늘

#154 refactor: RequestBody DTO 수정 및 신청 프로세스 API lessonId 삭제
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: 🔨 Refactor, BE이규리

#165 refactor: 결제 PaymentInfo 저장 시 Suggest 정보 같이 저장
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/ReadyToPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: 🔨 Refactor, BE이규리

#157 feat: 로그인 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/AuthDto.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/TokenDto.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/provider/JwtAuthenticationProvider.java
  server/src/main/java/com/codueon/boostUp/global/security/token/JwtAuthenticationToken.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
  server/src/main/java/com/codueon/boostUp/security/config/SecurityConfig.java
  server/src/test/java/com/codueon/boostUp/domain/member/auth/JwtTokenUtilsTest.java
Labels: ⛲ Feature, 👽️ API, BE임재민

#167 feat: Lesson 등록 구현 완료
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/CareerImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/AddressRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CareerImageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CurriculumRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LanguageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonAddressRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonInfoRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonLanguageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/ProfileImageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
Labels: ⛲ Feature, 👽️ API, BE주석영

#171 refactor: Lesson Controller postLesson @RequestPart 부분에 file,files 부분 각각 profileImage,careerImage로 변경
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#172 feat: resetPassword auth component 구현
  client/components/reuse/AuthBtn.tsx
  client/components/reuse/AuthContainer.tsx
  client/components/reuse/FormInputBox.tsx
  client/components/reuse/NewAuthBtn.tsx
  client/package-lock.json
  client/package.json
  client/pages/resetPassword.tsx
  client/tailwind.config.js
Labels: ⛲ Feature, FE박성훈

#175 feat: 채팅 기능 구현 중
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/ChatRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/RoomService.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PatchMember.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#177 refactor: Lesson Controller 분리 작업
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#178 feat: 결제 기능, 과외 종료 기능 구현 및 주석 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/KakaoPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/Amount.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/CardInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/PaySuccessInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/RequestForPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/PaymentInfoRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#180 refactor: createLesson 리펙토링중
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: 🔨 Refactor, BE주석영

#181 refactor: 과외 등록 리팩터링 및 오류 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchContoller.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonAddress.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonLanguage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/SearchService.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
Labels: 🚨 BugFix, 🔨 Refactor, BE조경민

#189 feat: 과외 home 조회 및 상세페이지 정보 조회 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchContoller.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonDetail.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetMainPageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CurriculumRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonInfoRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/SearchService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE조경민

#187 feat: reset pw page#155
  client/.gitignore
  client/apis/auth/postAuthPw.tsx
  client/atoms/auth/authAtom.tsx
  client/components/auth/ResetPwAuth.tsx
  client/components/auth/ResetPwSet.tsx
  client/components/reuse/AuthContainer.tsx
  client/hooks/auth/usePostAuthPw.tsx
  client/pages/resetPassword.tsx
Labels: ⛲ Feature, FE박성훈

#190 feat: 헤더 컴포넌트 작성
  client/assets/color/color.ts
  client/assets/icon/Exit.tsx
  client/assets/icon/Magnify.tsx
  client/atoms/index.tsx
  client/components/Header/Header.tsx
  client/components/Header/SearchPop.tsx
  client/components/reuse/AuthBtn.tsx
  client/components/reuse/InputBox.tsx
  client/components/reuse/dict.ts
  client/package-lock.json
  client/package.json
  client/pages/test.tsx
Labels: ⛲ Feature, 🖼 HTML&CSS, FE김상현

#191 feat: 로그인회원가입퍼블리싱 #156
  client/pages/login.tsx
  client/pages/signup.tsx
Labels: ⛲ Feature, FE정하늘

#193 feat: 페이지 조립
  client/pages/_app.tsx
Labels: 🖼 HTML&CSS, FE김상현, FE정하늘, FE박성훈

#194 refactor: 마이페이지 조회 시 ProfileImage 나오도록 주석 삭제 및 PaymentInfo 중복 저장 방지 로직 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetSuggestInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: 🔨 Refactor, BE이규리

#197 style: input태그 rounded값 xl로 수정
  client/components/auth/ResetPwAuth.tsx
  client/components/auth/ResetPwSet.tsx
  client/pages/login.tsx
  client/pages/signup.tsx
Labels: 🖼 HTML&CSS, FE박성훈

#198 test: Payment 결제 Test 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/PaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: BE이규리, ✅ Test

#202 style: reset Css
  client/styles/globals.css
Labels: 🖼 HTML&CSS, FE박성훈

#201 feat: 카테고리 검색 및 상세 검색 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchContoller.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetTutorLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/SearchService.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#205 feat: createModal Container
  client/components/reuse/CreateModalContainer.tsx
  client/pages/index.tsx
  client/styles/globals.css
Labels: ⛲ Feature, FE박성훈

#219 refactor: Lesson(Get) 검색 조건 및 Controller API 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
Labels: 🚨 BugFix, 🔨 Refactor, BE조경민

#220 test: Lesson 조회 기능 Controller 테스트 완료
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetDetailPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMainPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMyPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/SearchControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: 🔨 Refactor, BE조경민, ✅ Test

#221 헤더 css 수정
  client/components/Header/Header.tsx
  client/components/Header/SearchPop.tsx
  client/components/reuse/AuthBtn.tsx
Labels: ⛲ Feature, 🖼 HTML&CSS, 🔨 Refactor, FE김상현

#222 feat: 글작성모달 재사용 컴포넌트 구현
  client/atoms/main/mainAtom.tsx
  client/components/Header/SearchPop.tsx
  client/components/auth/ResetPwAuth.tsx
  client/components/auth/ResetPwSet.tsx
  client/components/reuse/btn/AuthBtn.tsx
  client/components/reuse/btn/NewAuthBtn.tsx
  client/components/reuse/btn/SmallBtn.tsx
  client/components/reuse/container/AuthContainer.tsx
  client/components/reuse/container/CreateModalContainer.tsx
  client/components/reuse/container/StepNavWrapper.tsx
  client/components/reuse/input/FormInputBox.tsx
  client/components/reuse/input/InputBox.tsx
  client/components/reuse/step/BasicStep.tsx
  client/components/reuse/step/CurrStep.tsx
  client/components/reuse/step/ExtraStep.tsx
  client/pages/index.tsx
  client/pages/login.tsx
  client/pages/resetPassword.tsx
  client/pages/signup.tsx
Labels: ⛲ Feature, 🖼 HTML&CSS, FE박성훈

#223 feat: lesson 수정 구현중
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostEditLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CareerImageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonAddressRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonLanguageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/ProfileImageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
Labels: ⛲ Feature, 👽️ API, BE주석영

#224 refactor: 과외 요약 정보 수정 구현 완료
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#225 feat: Toss 결제 URL 요청 기능 구현 및 카카오페이 결제 코드 수정
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/KakaoPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/TossPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/Checkout.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/KakaoPayReadyInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/KakaoPaySuccessInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/ReadyToKakaoPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/ReadyToTossPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/RequestForKakaoPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/TossPayHeader.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/TossPayReadyInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/utils/PayConstants.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#229 feat: 과외 상세정보 수정 구현 완료
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonDetailEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, BE주석영

#233 feat: 과외 커리큘럼 수정 구현 완료
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, BE주석영

#236 feat: 과외 삭제 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonInfoRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
Labels: ⛲ Feature, 👽️ API, BE주석영

#237 feat: 비밀번호 재설정(본인 확인) 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostAttemptFindPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetAllDetailReviews.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE조경민

#239 feat: 과외 등록 이미지 S3에 업로드로 변경 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#240 feat: Toss 결제 승인/취소 기능 구현 및 API 주소 수정
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/KakaoPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/TossPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/Amount.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/KakaoCard.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayHeader.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayReadyInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPaySuccessInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/ReadyToKakaoPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/RequestForKakaoPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/CardInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/KakaoPayHeader.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/ReadyToKakaoPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/ReadyToTossPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/RequestForKakaoPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/TossPayHeader.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/pay/TossPayReadyInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/Checkout.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/MobilePhone.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/ReadyToTossPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/Receipt.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/RequestForTossPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/TossCard.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/TossPayHeader.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/TossPayReadyInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/TossPaySuccessInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/Transfer.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/utils/SuggestConstants.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE이규리

#242 feat : Redis 적용
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/provider/JwtAuthenticationProvider.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/AuthConstants.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/RedisUtils.java
Labels: ⛲ Feature, 👽️ API, BE임재민

#243 test: Payment 결제 Test 코드 작성
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/PaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
Labels: BE이규리, ✅ Test

#244 feat: 회원 중복 검사/비밀번호 변경 구현
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostChangePassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostEmail.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostName.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberImage.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
Labels: BE조경민

#248 refactor: API 명세 변경으로 인한 MemberController API Refactoring
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
Labels: 🔨 Refactor, BE조경민

#247 refactor: Lesson 도메인 API 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
Labels: 🔨 Refactor, BE이규리

#253 feat: S3 과외 프로필 이미지 수정 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/global/file/AwsS3Service.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#256 feat: 글작성모달 진행방식 컴포넌트 구현
  client/apis/auth/postAuthPw.tsx
  client/components/createModal/Curriculum.tsx
  client/components/reuse/btn/SmallBtn.tsx
  client/components/reuse/container/CreateModalContainer.tsx
  client/hooks/useWindowSize.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/styles/globals.css
Labels: FE박성훈

#255 feat: 글작성 모달 추가정보 구현
  client/assets/color/color.ts
  client/assets/icon/DefaultImg.tsx
  client/components/Additional.tsx
  client/components/Header/Header.tsx
  client/components/comp.tsx
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/tailwind.config.js
Labels: ⛲ Feature, 🖼 HTML&CSS, FE김상현

#263 Feat/footer#260
  client/components/Footer/Footer.tsx
  client/components/Header/Header.tsx
  client/next.config.js
  client/pages/_app.tsx
Labels: ⛲ Feature, 🖼 HTML&CSS, FE김상현

#265 refactor: searchController api URL 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchController.java
Labels: 🔨 Refactor, BE조경민

#266 refactor: Cors 이슈에 따른 SecurityConfig 설정 수정
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
Labels: 🔨 Refactor, BE조경민

#269 feat: 이메일 인증 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatMember.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetLastChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/ChatRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/RoomService.java
  server/src/main/java/com/codueon/boostUp/domain/dto/PostEmail.java
  server/src/main/java/com/codueon/boostUp/domain/dto/PostPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
  server/src/main/java/com/codueon/boostUp/global/config/EmailConfig.java
  server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
  server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
  server/src/main/java/com/codueon/boostUp/global/event/email/controller/EmailController.java
  server/src/main/java/com/codueon/boostUp/global/event/email/dto/PostEmailCode.java
  server/src/main/java/com/codueon/boostUp/global/event/email/service/EmailService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/RedisUtils.java
  server/src/main/java/com/codueon/boostUp/global/utils/Auditable.java
  server/src/main/java/com/codueon/boostUp/global/utils/RedisUtils.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#270 feat: 과외 삭제 시 S3에 이미지 삭제 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#279 feat : 기본정보 입력 페이지 #203
  client/components/createModal/BasicInfo.tsx
  client/pages/index.tsx
  client/pages/signup.tsx
Labels: ⛲ Feature, FE정하늘

#282 feat: 캐러셀 1차구현 완료
  client/apis/auth/postAuthPw.tsx
  client/components/carousel/Carouselcomp.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/public/images/temp_image.png
  client/styles/globals.css
Labels: ⛲ Feature, 🖼 HTML&CSS, FE박성훈

#281 feat: getPaymentReceipt 결제 영수증 조회 기능 구현 및 선생님 마이페이지 조회 조건 수정
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#284 fix: 캐러셀 resizing
  client/components/carousel/Carouselcomp.tsx
  client/pages/index.tsx
Labels: 🚨 BugFix, FE박성훈

#285 feat: 비밀번호 찾기 및 변경 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/dto/PostEmail.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostEmail.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPasswordInLoginPage.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPasswordInMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/global/event/email/controller/EmailController.java
  server/src/main/java/com/codueon/boostUp/global/event/email/service/EmailService.java
  server/src/main/java/com/codueon/boostUp/global/utils/RedisUtils.java
Labels: ⛲ Feature, 👽️ API, BE조경민

#287 feat: Init Chat Server
  chat-server/.gitignore
  chat-server/build.gradle
  chat-server/gradle/wrapper/gradle-wrapper.jar
  chat-server/gradle/wrapper/gradle-wrapper.properties
  chat-server/gradlew
  chat-server/settings.gradle
  chat-server/src/main/java/com/codueon/chatserver/ChatServerApplication.java
  chat-server/src/main/resources/application.properties
  chat-server/src/test/java/com/codueon/chatserver/ChatServerApplicationTests.java
Labels: ⚙Setting, BE조경민

#288 test: Suggest 영수증 조회 Test 코드 작성 및 Suggest Get 리팩토링
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: BE이규리, ✅ Test

#290 feat: 마이페이지 등록한 과외 조회 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/SearchService.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/SearchControllerTest.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#295 feat: postChangeMemberInfoInMyPage 회원 정보 수정 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PatchMember.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/global/file/AwsS3Service.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#301 Feat/navbar#276
  client/assets/icon/IconChat.tsx
  client/assets/icon/IconCode.tsx
  client/assets/icon/IconExit.tsx
  client/assets/icon/IconHome.tsx
  client/assets/icon/IconImg.tsx
  client/assets/icon/IconMagnify.tsx
  client/assets/icon/IconPlus.tsx
  client/assets/icon/IconProfile.tsx
  client/assets/icon/index.tsx
  client/components/Footer/Footer.tsx
  client/components/Header/Header.tsx
  client/components/Header/SearchPop.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Additional.tsx
  client/pages/_app.tsx
  client/pages/index.tsx
Labels: ⛲ Feature, 🖼 HTML&CSS, FE김상현

#303 refactor: 불필요한 PayNember 제거 및 PaymentMethod 저장 방식 변경
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: 🔨 Refactor, BE이규리

#304 feat : 로그인 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetailService.java
  server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetails.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/provider/JwtAuthenticationProvider.java
  server/src/main/java/com/codueon/boostUp/global/security/token/JwtAuthenticationToken.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
Labels: ⛲ Feature, 👽️ API, BE임재민

#306 feat: 출석부 조회/출석인정/출석인정취소 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#312 feat: 채팅 Stomp 테스트(테스트 서버 추가)
  chat-server/build.gradle
  chat-server/src/main/java/com/codueon/chatserver/ChatServerApplication.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/controller/MessageController.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/controller/WSController.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/dto/Message.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/dto/ResponseMessage.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/handler/UserHandshakeHandler.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/service/ChatService.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/service/NotificationService.java
  chat-server/src/main/java/com/codueon/chatserver/domain/chat/service/WebSocketService.java
  chat-server/src/main/java/com/codueon/chatserver/domain/member/entity/AccountStatus.java
  chat-server/src/main/java/com/codueon/chatserver/domain/member/entity/Member.java
  chat-server/src/main/java/com/codueon/chatserver/domain/member/entity/MemberImage.java
  chat-server/src/main/java/com/codueon/chatserver/domain/member/entity/MemberStatus.java
  chat-server/src/main/java/com/codueon/chatserver/domain/member/feign/MemberFeignService.java
  chat-server/src/main/java/com/codueon/chatserver/domain/member/repository/MemberRepository.java
  chat-server/src/main/java/com/codueon/chatserver/domain/member/service/MemberService.java
  chat-server/src/main/java/com/codueon/chatserver/global/config/WebSocketConfig.java
  chat-server/src/main/java/com/codueon/chatserver/global/exception/BusinessLogicException.java
  chat-server/src/main/java/com/codueon/chatserver/global/exception/ErrorResponse.java
  chat-server/src/main/java/com/codueon/chatserver/global/exception/ExceptionCode.java
  chat-server/src/main/java/com/codueon/chatserver/global/exception/GlobalAdvice.java
  chat-server/src/main/java/com/codueon/chatserver/global/util/Auditable.java
  chat-server/src/main/java/com/codueon/chatserver/global/webhook/SendErrorToDiscord.java
  chat-server/src/main/java/com/codueon/chatserver/global/webhook/ServiceError.java
  chat-server/src/main/java/com/codueon/chatserver/global/webhook/WebHookError.java
  chat-server/src/main/java/com/codueon/chatserver/global/webhook/WebHookFeign.java
  chat-server/src/main/resources/application.properties
  chat-server/src/main/resources/static/index.html
  chat-server/src/main/resources/static/scripts.js
  server/.gitignore
  server/src/main/java/com/codueon/boostUp/domain/chat/constant/MessageType.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetChatMember.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetLastChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/PostMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/PostRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/ChatRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/RoomService.java
  server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
  server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetDetailPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMyPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
Labels: ⛲ Feature, 👽️ API, BE조경민, ✅ Test

#314 refactor: 출석부 조회 시 Response 데이터 변경
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetLessonAttendance.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: 🔨 Refactor, BE이규리

#315 test: 과외 등록 테스트 작성
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonTest.java
Labels: BE주석영, ✅ Test

#316 feat: Toss 환불 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/TossPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/CancelToTossPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/Cancels.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/TossPayCancelInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/utils/PayConstants.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#319 test: 출석부 조회/출석인정/출석인정취소 Test 코드 작성
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: BE이규리, ✅ Test

#322 feat : 로그아웃 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/AccountStatus.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
  server/src/main/java/com/codueon/boostUp/global/utils/RedisUtils.java
Labels: ⛲ Feature, 👽️ API, BE임재민

#327 feat : 언어필터컴포넌트 api연결 제외 구현 완료
  client/atoms/main/mainAtom.tsx
  client/components/carousel/Carouselcomp.tsx
  client/components/filter/LanguageFilter.tsx
  client/components/filter/MobileLanguageFilter.tsx
  client/components/reuse/dict.ts
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/public/images/C.png
  client/public/images/go.png
  client/public/images/java.png
  client/public/images/javascript.png
  client/public/images/kotlin.png
  client/public/images/php.png
  client/public/images/python.png
  client/public/images/swift.png
  client/tailwind.config.js
Labels: ⛲ Feature, 🖼 HTML&CSS, FE박성훈

#328 test: 과외 요약 수정 테스트 & restDocs 문서 자동화
  server/src/asciidoc/index.adoc
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/UpdateLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: 📄 Docs, BE주석영, ✅ Test

#330 test: 과외 상세 수정 테스트 & restDocs 문서 자동화
  server/src/asciidoc/index.adoc
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonDetailEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonDetailEditTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonInfoEditTest.java
Labels: 📄 Docs, BE주석영, ✅ Test

#340 test : 과외 삭제 테스트 & 문서 자동화
  server/src/asciidoc/index.adoc
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/DeleteLessonTest.java
Labels: 📄 Docs, BE주석영, ✅ Test

#342 test: Suggest Test Rest Docs 적용
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayCancelInfo.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: BE이규리, ✅ Test

#349 refactor: lesson controller Authentication token 적용
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonDetailEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMainPageLessonTest.java
Labels: 🔨 Refactor, BE주석영

#352 refactor: lesson dto 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonTest.java
Labels: 🔨 Refactor, BE주석영

#355 feat: 인증페이지 api연결
  client/apis/auth/postAuthCode.tsx
  client/apis/auth/postAuthEmail.tsx
  client/apis/auth/postAuthPw.tsx
  client/apis/auth/postLogin.tsx
  client/apis/auth/postResetPw.tsx
  client/apis/auth/postSignUp.tsx
  client/apis/board/getFilteredBoard.tsx
  client/atoms/auth/authAtom.tsx
  client/components/auth/ResetPwCodeAuth.tsx
  client/components/auth/ResetPwEmailAuth.tsx
  client/components/auth/ResetPwSet.tsx
  client/components/filter/MobileLanguageFilter.tsx
  client/hooks/auth/usePostAuthPw.tsx
  client/hooks/auth/usePostCodeAuth.tsx
  client/hooks/auth/usePostEmailAuth.tsx
  client/hooks/auth/usePostLogin.tsx
  client/hooks/auth/usePostResetPw.tsx
  client/hooks/auth/usePostSignUp.tsx
  client/pages/login.tsx
  client/pages/resetPassword.tsx
  client/pages/signup.tsx
Labels: ⛲ Feature, FE박성훈

#358 feat: 비밀번호변경 관련 이메일존재여부 확인기능 구현
  client/apis/auth/postCheckEmail.tsx
  client/components/auth/ResetPwCodeAuth.tsx
  client/components/auth/ResetPwEmailAuth.tsx
  client/hooks/auth/usePostCheckEmail.tsx
  client/hooks/auth/usePostCodeAuth.tsx
Labels: ⛲ Feature, FE박성훈

#361 refactor: Suggest authentication 토큰 리펙토링 및 Member 수정 반환데이터 생성
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberImage.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
Labels: 🔨 Refactor, BE이규리

#370 refactor: language, address 테이블 삭제
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetMainPageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetTutorLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonInfoEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Address.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/AddressInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/CareerImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LanguageInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonAddress.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonLanguage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/AddressRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LanguageRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetRefundPayment.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/resources/db/h2/import.sql
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: 🚨 BugFix, 🔨 Refactor, BE조경민

#359 feat/mainpage card#280 (메인 카드 통신 1차 업로드)
  client/apis/card/getMainCard.tsx
  client/assets/icon/IconPaper.tsx
  client/assets/icon/IconPlace.tsx
  client/assets/icon/IconRibbon.tsx
  client/assets/icon/IconWon.tsx
  client/assets/icon/index.tsx
  client/components/Card/card.tsx
  client/components/Card/useGetMainCard.tsx
  client/components/createModal/Additional.tsx
  client/components/createModal/BasicInfo.tsx
  client/package.json
  client/pages/card.tsx
  client/pages/index.tsx
  client/pages/login.tsx
Labels: ⛲ Feature, FE정하늘

#369 feat: 상세페이지 재사용컴포넌트 구현
  client/atoms/detail/detailAtom.tsx
  client/components/reuse/btn/DetailBtn.tsx
  client/components/reuse/btn/DetailTabBtn.tsx
  client/components/reuse/container/DetailContentContainer.tsx
  client/components/reuse/container/DetailSummeryContainer.tsx
  client/pages/detail/[id].tsx
Labels: ⛲ Feature, 🖼 HTML&CSS, FE박성훈

#372 refactor: Suggest QueryDSL 수정 및 주소, 언어 타입 변경으로 인한 테스트 코드 리팩토링
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetLessonAttendance.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetTutorSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostPaymentUrl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostReason.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Reason.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/SuggestStatus.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/FeignErrorConfig.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/KakaoPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/TossPayFeignClient.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/feign/getFeignClientUtils.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPaySuccessInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/PaymentInfoRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/toss/Cancels.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/utils/PayConstants.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/utils/SuggestConstants.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/AuthConstants.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/MyPageBookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/DeleteLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetDetailPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMainPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMyPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PatchLessonCurriculumTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonDetailEditTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonInfoEditTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
Labels: 🔨 Refactor, BE이규리, ✅ Test

#371 [FE] Feat/write modal#302
  client/apis/postWrite.tsx
  client/assets/icon/IconProfile.tsx
  client/atoms/main/mainAtom.tsx
  client/components/Header/Header.tsx
  client/components/Header/SearchPop.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Additional.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/createModal/Curriculum.tsx
  client/components/createModal/WriteModal.tsx
  client/components/reuse/CreateModalContainer.tsx
  client/components/reuse/btn/SmallBtn.tsx
  client/components/reuse/container/ModalBackDrop.tsx
  client/components/reuse/dict.ts
  client/components/reuse/step/BasicStep.tsx
  client/components/reuse/step/CurrStep.tsx
  client/components/reuse/step/ExtraStep.tsx
  client/hooks/usePostWrite.tsx
  client/package.json
  client/pages/index.tsx
  client/tailwind.config.js
  client/tsconfig.json
Labels: FE김상현

#378 feat: AWS EC2 서버 구축
  server/.gitignore
  server/Dockerfile
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/global/actuator/HealthCheck.java
  server/src/main/resources/application.yml
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, ⚙Setting, BE조경민

#379 refactor: build.gradle queryDsl 수정
  server/build.gradle
  server/src/main/resources/application-server.yml
Labels: 🔨 Refactor, BE조경민

#380 refactor: lesson 수정 리팩터링 중
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: 🔨 Refactor, BE주석영

#382 refactor: build.gradle aws parameter store dependency 추가
  server/build.gradle
Labels: 🔨 Refactor, BE조경민

#383 fix: aws parameter store dependency 충돌 수정
  server/build.gradle
Labels: 🚨 BugFix, BE조경민

#384 test: branch 테스트
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
Labels: BE조경민, ✅ Test

#386 test: 전체 도메인 Rest Docs Test 코드 작성
  server/src/asciidoc/index.adoc
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/MyPageBookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetDetailPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMyPageLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonDetailEditTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonInfoEditTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonTest.java
  server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberCreateTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/ApiDocumentUtils.java
Labels: BE이규리, ✅ Test

#390 refactor: lesson 수정 리팩터링 완료
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/CareerImageVO.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonDetailEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/CareerImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonInfoRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/resources/static/index.html
  server/src/main/resources/static/scripts.js
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor

#391 refactor: 실수로 지워진 static폴더 복구
  server/src/main/resources/static/index.html
  server/src/main/resources/static/scripts.js
Labels: 🔨 Refactor, BE주석영

#392 refactor: 과외 등록 시 한 멤버당 하나의 과외만 등록 가능하게 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/resources/application.yml
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#399 refactor : lesson 토큰 부분 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
Labels: 🔨 Refactor, BE주석영

#397 Refactor/style nmodal#376
  client/atoms/auth/authAtom.tsx
  client/atoms/index.tsx
  client/components/Footer/Footer.tsx
  client/components/Header/Header.tsx
  client/components/Header/SearchPop.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Curriculum.tsx
  client/components/createModal/ExtraInfo.tsx
  client/components/createModal/WriteModal.tsx
  client/components/filter/MobileLanguageFilter.tsx
  client/hooks/auth/usePostLogin.tsx
  client/package-lock.json
  client/package.json
Labels: 🔨 Refactor, FE김상현

#404 refactor : lesson 로컬 이미지 수정 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#405 refactor: lesson.getName()->member.getName() 수정 및 Suggest 반환 데이터 수정
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetQuantityCount.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetRefundPayment.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: 🔨 Refactor, BE이규리

#406 refactor : 마이페이지 등록한 과외 조회 url 랩핑 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/WrapUrl.java
Labels: 🔨 Refactor, BE주석영

#407 refactor : 과외 수정 시 해당 멤버만 수정할 수 있는 로직 추가
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#408 refactor: parameter store gradle 수정
  server/Dockerfile
  server/src/main/resources/bootstrap.yml
Labels: 🔨 Refactor, ⚙Setting, BE조경민

#410 fix: Test 통과 오류 나던 부분 수정
  server/src/main/java/com/codueon/boostUp/global/utils/Auditable.java
  server/src/test/java/com/codueon/boostUp/BoostUpApplicationTests.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: 🔨 Refactor, BE조경민, ✅ Test

#412 refactor: 테스트 통과 안되던 문제 수정
  server/src/main/java/com/codueon/boostUp/global/utils/Auditable.java
  server/src/test/java/com/codueon/boostUp/BoostUpApplicationTests.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: 🔨 Refactor, BE조경민

#415 refactor: review Test 수정
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
Labels: 🔨 Refactor, ⚙Setting, BE조경민

#417 refactor: server 재발돼라
  server/build.gradle
  server/src/main/resources/application.yml
Labels: 🔨 Refactor, BE조경민

#428 refactor: Review, Bookmark authentication 수정
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPatchTest.java
Labels: 🔨 Refactor, BE이규리

#429 refactor : lessonService 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#431 refactor: webhook 임시 제거
  server/src/main/java/com/codueon/boostUp/global/exception/GlobalAdvice.java
  server/src/main/java/com/codueon/boostUp/global/webhook/WebHookFeign.java
  server/src/main/resources/application-prod.yml
  server/src/main/resources/application-server.yml
Labels: 🔨 Refactor, BE조경민

#434 feat: JWT 토큰 재발급 구현
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetailService.java
  server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetails.java
  server/src/main/java/com/codueon/boostUp/global/security/details/OAuth2DetailService.java
  server/src/main/java/com/codueon/boostUp/global/security/dto/ClaimsVO.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/codueon/boostUp/global/security/handler/OAuth2FailureHandler.java
  server/src/main/java/com/codueon/boostUp/global/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/codueon/boostUp/global/security/oauth/OAuth2Attribute.java
  server/src/main/java/com/codueon/boostUp/global/security/provider/JwtAuthenticationProvider.java
  server/src/main/java/com/codueon/boostUp/global/security/token/JwtAuthenticationToken.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/AuthConstants.java
  server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
  server/src/main/java/com/codueon/boostUp/global/utils/RedisUtils.java
Labels: ⛲ Feature, BE임재민

#435 refactor : lessonService 리팩터링
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#439 refactor: Authentication 변경에 따른 Token 정보 수정
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
Labels: 🔨 Refactor, BE조경민, ✅ Test

#444 feat: 상세페이지 요약정보
  client/apis/detail/getBasicInfo.tsx
  client/assets/icon/detailSummeryIcon/AreaIcon.tsx
  client/assets/icon/detailSummeryIcon/CareerIcon.tsx
  client/assets/icon/detailSummeryIcon/CompanyIcon.tsx
  client/assets/icon/detailSummeryIcon/NickNameIcon.tsx
  client/atoms/detail/detailAtom.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailBasicInfoEditModal.tsx
  client/components/detailComp/MobileDetailBasicInfo.tsx
  client/components/reuse/container/DetailSummeryContainer.tsx
  client/hooks/detail/useGetBasicInfo.tsx
  client/pages/detail/[id].tsx
Labels: FE박성훈

#445 Feat/상세페이지 추가정보 및 진행상황
  client/apis/detail/getCurriculum.tsx
  client/apis/detail/getExtra.tsx
  client/apis/detail/postExtraModi.tsx
  client/components/DetailCurriculum.tsx
  client/components/DetailExtra.tsx
  client/components/DetailExtraModi.tsx
  client/components/Footer/Footer.tsx
  client/components/Header/Header.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Curriculum.tsx
  client/components/reuse/btn/DetailTabBtn.tsx
  client/hooks/detail/useGetCurriculum.tsx
  client/hooks/detail/useGetExtra.tsx
  client/hooks/detail/usePostExtraModi.tsx
  client/hooks/usePostWrite.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/detail/[id].tsx
  client/pages/index.tsx
  client/postcss.config.js
  client/styles/globals.css
Labels: FE김상현

#451 refactor : lesson에 name 제거 하면서 전반적인 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetMainPageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetTutorLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#452 refactor: Review N+1 문제 해결
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
  server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberImage.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/resources/application-prod.yml
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: 🚨 BugFix, 🔨 Refactor, BE조경민, ✅ Test

#453 refactor: 조회 query 수정 및 Suggest 단건 조회 QueryDSL 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: 🔨 Refactor, BE이규리

#454 refactor: review 버그 픽스
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
Labels: 🚨 BugFix, 🔨 Refactor, BE조경민

#455 refactor : 북마크 N+1 관련 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#457 refactor : 과외 상세페이지 요약 정보 조회 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#458 refactor: Lesson 쿼리 수정
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
Labels: 🚨 BugFix, BE조경민

#462 refactor: redis config 임시 분리
  server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
  server/src/main/java/com/codueon/boostUp/global/handler/StompHandler.java
  server/src/main/resources/static/index.html
  server/src/main/resources/static/scripts.js
Labels: 🔨 Refactor, BE조경민

#464 refactor : 과외 dto 폴더 정리
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetLessonCurriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetMainPageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetStudentLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetTutorLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetTutorMypageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PatchLessonCurriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonDetailEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonInfoEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/etc/CareerImageVO.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/etc/WrapUrl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
Labels: 🔨 Refactor, BE주석영

#465 refactor: Suggest 중복 등록 방지 메서드 추가 및 Suggest 수정
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetRefundPayment.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
Labels: 🔨 Refactor, BE이규리

#467 feat: 상세페이지 요약정보 모달 1차구현
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailBasicInfoEditModal.tsx
  client/pages/detail/[id].tsx
Labels: ⛲ Feature, FE박성훈

#468 feat: 상세페이지 - 추가정보 및 진행방식 - 진행상황 merge
  client/apis/card/getMainCard.tsx
  client/apis/detail/postDetailModi.tsx
  client/components/DetailCurriculum.tsx
  client/components/Header/Header.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Curriculum.tsx
  client/components/createModal/ExtraInfo.tsx
  client/components/createModal/WriteModal.tsx
  client/components/detailComp/DetailCurModi.tsx
  client/components/detailComp/DetailCurriculum.tsx
  client/components/detailComp/DetailExtra.tsx
  client/components/detailComp/DetailExtraModi.tsx
  client/hooks/detail/useGetCurriculum.tsx
  client/hooks/detail/usePostCurModi.tsx
  client/package-lock.json
  client/package.json
  client/pages/detail/[id].tsx
  client/styles/globals.css
  client/tailwind.config.js
Labels: FE김상현

#476 feat: 상세페이지 요약정보 수정모달 api제외 구현완료
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailBasicInfoEditModal.tsx
  client/components/reuse/container/CreateModalContainer.tsx
  client/components/reuse/container/ModalBackDrop.tsx
  client/pages/detail/[id].tsx
Labels: ⛲ Feature, FE박성훈

#480 refactor: JWT 토큰 잘못되던 부분 수정
  server/images/13291250119791.jpg
  server/images/13291258123458.jpg
  server/images/13291258299333.jpg
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
  server/src/main/resources/static/index.html
Labels: 🔨 Refactor, BE조경민

#481 feat: 상세페이지 과외후기 구현완료
  client/apis/detail/getDetailReview.tsx
  client/atoms/detail/detailAtom.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/createModal/Curriculum.tsx
  client/components/createModal/WriteModal.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailReview.tsx
  client/hooks/detail/useGetDetailReview.tsx
  client/pages/detail/[id].tsx
Labels: FE박성훈

#485 refactor : 과외 요약 정보 수정 프로필 이미지 리팩터링
  server/images/13291250119791.jpg
  server/images/13291258123458.jpg
  server/images/13291258299333.jpg
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#487 Style/shop#486 결제페이지 목업
  client/components/detailComp/DetailExtra.tsx
  client/components/mypage/MypageInfo.tsx
  client/pages/detail/[id].tsx
  client/pages/mypage/[id].tsx
  client/pages/shop.tsx
Labels: 🖼 HTML&CSS, FE김상현

#488 Feat/mypagepublish#475
  client/assets/icon/IconMail.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/MypageInfo.tsx
  client/components/Mypage/StudentBookmark.tsx
  client/components/Mypage/StudentClass.tsx
  client/components/Mypage/StudentReview.tsx
  client/components/Mypage/StudentTab.tsx
  client/components/Mypage/TeacherTab.tsx
  client/components/mypage/MypageInfo.tsx
Labels: ⛲ Feature, FE정하늘
