Repository boostup-project/boostup-project, pull requests merged in 2023-02, with the labels that each got.

#496 feat: 결제 여부 조회 메서드 구현 및 이용권 1차 구현
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/WrapPaymentStatusCheck.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/WrapQuantityCount.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Purchase.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PurchaseStatus.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Ticket.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/PurchaseRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/resources/db/h2/Ticket.sql
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#497 refactor : 과외 요약정보 조회 시 토큰값으로 수정 가능한지 비교하는 로직 추가
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#498 refactor: 사용자 프로필 수정 시 디폴트 이미지를 제외한 기존 S3 이미지 삭제
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
Labels: 🔨 Refactor, BE이규리

#499 refactor : 과외 요약 정보 수정시 프로필 이미지 수정 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonInfoEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#502 feat: 이용권 구현 2 - 이용권 구매 시 정렬
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetMainPageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Purchase.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Ticket.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/TicketRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/resources/db/h2/Ticket.sql
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
Labels: ⛲ Feature, BE이규리

#504 refactor: 학생 신청 내역 삭제 예외처리 수정
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: 🔨 Refactor, BE이규리

#506 refactor: 과외 언어별 조회 QueryDSL 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
Labels: 🔨 Refactor, BE이규리

#509 Feat/pay feat#489 결제페이지 및 영수증 페이지 구현
  client/apis/detail/postCurModi.tsx
  client/apis/shop/getKakaoNTossPay.tsx
  client/apis/shop/getPaymentCheck.tsx
  client/apis/shop/getPaymentInfo.tsx
  client/apis/shop/getReceipt.tsx
  client/components/Header/Header.tsx
  client/components/Navbar/Navbar.tsx
  client/hooks/detail/usePostCurModi.tsx
  client/hooks/shop/useGetKakaoNTossPay.tsx
  client/hooks/shop/useGetPaymentCheck.tsx
  client/hooks/shop/useGetPaymentInfo.tsx
  client/hooks/shop/useGetReceipt.tsx
  client/package-lock.json
  client/package.json
  client/pages/shop.tsx
  client/pages/shop/[id]/index.tsx
  client/pages/shop/[id]/receipt.tsx
Labels: ⛲ Feature, 🖼 HTML&CSS, FE김상현

#510 fix: tanstack query import 문으로 대체
  client/hooks/shop/useGetKakaoNTossPay.tsx
  client/hooks/shop/useGetPaymentCheck.tsx
  client/hooks/shop/useGetPaymentInfo.tsx
  client/hooks/shop/useGetReceipt.tsx
Labels: 🚨 BugFix, FE김상현

#514 refactor : GetLesson editable 토큰 String null일때 null처리
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#516 refactor: 메인페이지 언어필터기능 연결완료
  client/atoms/main/mainAtom.tsx
  client/components/Maincard/Card.tsx
  client/components/Maincard/Cards.tsx
  client/components/filter/MobileLanguageFilter.tsx
  client/hooks/board/useGetFilteredBoard.tsx
Labels: FE박성훈

#517 Fix/header#512 - 헤더 검색창 해결 및 네브바 기능 추가
  client/apis/main/postSearch.tsx
  client/apis/main/postWrite.tsx
  client/assets/icon/IconLogIn.tsx
  client/assets/icon/index.tsx
  client/components/Header/Header.tsx
  client/components/Header/SearchPop.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Curriculum.tsx
  client/hooks/main/usePostSearch.tsx
  client/hooks/main/usePostWrite.tsx
  client/hooks/shop/useGetKakaoNTossPay.tsx
Labels: 🚨 BugFix, ⛲ Feature, FE김상현

#521 refactor: Lesson 조회 Query 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetMainPageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Purchase.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PurchaseStatus.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Ticket.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/PurchaseRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/TicketRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/resources/db/h2/Ticket.sql
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
Labels: 🔨 Refactor, BE이규리

#524 featMypageInfo기본정보호출수정
  client/components/Mypage/MypageInfo.tsx
Labels: FE정하늘

#529 refactor : 경력 이미지도 로컬에서 저장 시 uuid 적용
  server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
Labels: ⛲ Feature, 🔨 Refactor, BE주석영

#531 refactor: Member Controller Token 수정
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewDbService.java
Labels: 🔨 Refactor, BE이규리

#533 Feat/my page edit modal#518 - 정보수정 모달 완료
  client/apis/mypage/postMemberModi.tsx
  client/apis/mypage/postNameCheck.tsx
  client/components/Header/Header.tsx
  client/components/Mypage/EditUserData.tsx
  client/components/Mypage/MypageInfo.tsx
  client/components/createModal/WriteModal.tsx
  client/components/detailComp/DetailCurModi.tsx
  client/components/detailComp/DetailCurriculum.tsx
  client/components/detailComp/DetailExtra.tsx
  client/components/detailComp/DetailExtraModi.tsx
  client/components/reuse/CreateModalContainer.tsx
  client/components/reuse/container/CreateModalContainer.tsx
  client/hooks/mypage/usePostMemberModi.tsx
  client/hooks/mypage/usePostNameCheck.tsx
  client/pages/lesson/[id].tsx
Labels: 🚨 BugFix, ⛲ Feature, FE김상현

#532 fix: websocket CORS 이슈 수정
  server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
Labels: 🚨 BugFix, BE조경민

#534 feat my page teacher tab#513
  client/apis/mypage/getAllBookmark.tsx
  client/components/Detail/DetailButtons.tsx
  client/components/Header/Header.tsx
  client/components/Maincard/Card.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/ClassList.tsx
  client/components/Mypage/StudentBookmark.tsx
  client/components/Mypage/StudentClass.tsx
  client/hooks/detail/useGetBookmark.tsx
  client/hooks/mypage/useGetAllBookmark.tsx
  client/hooks/mypage/useGetMyTutor.tsx
  client/hooks/mypage/useGetStudentInfo.tsx
  client/pages/mypage/[name].tsx
  client/pages/shop/[id]/receipt.tsx
Labels: ⛲ Feature, FE정하늘

#535 refactor : 페이지 리사이징 및 이미지 최적화 작업
  client/apis/chat/postSendChat.tsx
  client/components/Detail/DetailButtons.tsx
  client/components/Footer/Footer.tsx
  client/components/Header/Header.tsx
  client/components/carousel/Carouselcomp.tsx
  client/components/chat/ChatComp.tsx
  client/components/chat/ChatContent.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/createModal/Curriculum.tsx
  client/components/filter/LanguageFilter.tsx
  client/hooks/chat/usePostSendChat.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/public/images/carousel/1.png
  client/public/images/carousel/2.png
  client/public/images/carousel/3.png
  client/public/images/carousel/4.png
  client/public/images/carousel/5.png
Labels: FE박성훈

#537 feat: 종료된 과외 삭제 기능 구현 및 코드 리팩토링
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewDbService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
Labels: ⛲ Feature, 👽️ API, BE이규리

#545 feat: 유효성 검사 추가
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonInfoEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostAttemptFindPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostEmail.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostLogin.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostMember.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostName.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPassword.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPasswordInLoginPage.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPasswordInMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PatchReview.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PostReview.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostPaymentUrl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostReason.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostSuggest.java
Labels: ⛲ Feature, BE이규리

#548 refactor: 북마크 dto 수정(career, company)
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
  server/src/main/resources/static/scripts.js
  server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: 🔨 Refactor, BE조경민

#551 feat: 회원 별 채팅방 구독 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/PostMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/AuthDto.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE조경민

#552 refactor: 과외 경력 이미지 리팩터링, 패키지 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLessonCurriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetMainPageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetStudentLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetTutorLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetTutorMypageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PatchLessonCurriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PostLessonDetailEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PostLessonImage.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PostLessonInfoEdit.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/post/PostLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/post/PostSearchLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/utils/CareerImageVO.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/utils/WrapUrl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/global/file/AwsS3Service.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#554 refactor: requestUrl 이슈 해결
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/resources/application-prod.yml
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
Labels: 🔨 Refactor, BE이규리

#556 refactor: 리뷰 쿼리 문제 수정
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
Labels: 🚨 BugFix, BE조경민

#558 refactor: Stomp 핸들러 수정
  server/src/main/java/com/codueon/boostUp/global/handler/StompHandler.java
Labels: 🚨 BugFix, BE조경민

#568 feat 마이페이지 스타일 수정
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/ClassList.tsx
  client/components/Mypage/EditUserData.tsx
  client/components/Mypage/EditUserPwd.tsx
  client/components/Mypage/FinishedClass.tsx
  client/components/Mypage/MypageInfo.tsx
  client/components/reuse/btn/MypageTabBtn.tsx
Labels: FE정하늘

#569 Refactor/things#567 리펙토링 진행상황
  client/components/Header/Header.tsx
  client/components/Header/SearchPop.tsx
  client/components/detailComp/MobileDetailBasicInfo.tsx
  client/components/filter/MobileLanguageFilter.tsx
  client/hooks/main/usePostWrite.tsx
Labels: FE김상현

#570 Feat/chat#484
  client/apis/chat/getChatList.tsx
  client/apis/chat/getChatRoomList.tsx
  client/apis/chat/getCreateRoom.tsx
  client/atoms/chat/chatAtom.tsx
  client/components/Detail/DetailButtons.tsx
  client/components/carousel/Carouselcomp.tsx
  client/components/chat/ChatComp.tsx
  client/components/chat/ChatContent.tsx
  client/components/chat/ChatListComp.tsx
  client/components/chat/ChatListContent.tsx
  client/components/chat/ChatReceiveMessage.tsx
  client/components/chat/ChatSendMessage.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailReview.tsx
  client/hooks/auth/usePostLogin.tsx
  client/hooks/chat/socket.tsx
  client/hooks/chat/useGetChatList.tsx
  client/hooks/chat/useGetChatRoomList.tsx
  client/hooks/chat/useGetCreateRoom.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/chat/[memberId].tsx
  client/pages/index.tsx
  client/pages/mypage/[name].tsx
Labels: ⛲ Feature, FE박성훈

#575 refactor: 회원 정보 수정 메서드 로컬/S3 분리
  server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/GetMemberEditInfo.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
Labels: 🔨 Refactor, BE이규리

#576 refactor : 마이페이지 등록한 과외 조회 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/utils/WrapLessonId.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/utils/WrapUrl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/resources/application-prod.yml
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor

#580 feat: 알람 기능 구현
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/AlarmController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRegisterController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRoomController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetAlarmMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/PostMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/SendMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendAlarmMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendAlarmMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendEnterMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendEnterRoomMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/querydsl/ChatRoomRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatAlarm.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/SendAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/SendMessageService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
  server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
  server/src/main/resources/static/index.html
  server/src/main/resources/static/scripts.js
Labels: ⛲ Feature, 👽️ API, BE조경민

#585 refactor: lesson Dto 수정
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatAlarm.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/SendAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLessonId.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetTutorMypageLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/utils/WrapLessonId.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/vo/CareerImageVO.java
Labels: 👽️ API, 🔨 Refactor, BE조경민

#586 fix: 채팅 알람 기능 오류 수정
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetAlarmMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/SendAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/SendMessageService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
  server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/token/JwtAuthenticationToken.java
  server/src/main/resources/static/scripts.js
Labels: 🚨 BugFix, BE조경민

#588 fix: 채팅방 연동 이슈 해결
  client/apis/chat/getResetChatAlarm.tsx
  client/atoms/chat/chatAtom.tsx
  client/components/chat/ChatComp.tsx
  client/components/chat/ChatContainer.tsx
  client/components/chat/ChatListComp.tsx
  client/components/chat/ChatListContent.tsx
  client/components/chat/ChatReceiveMessage.tsx
  client/components/chat/ChatSendMessage.tsx
  client/hooks/chat/socket.tsx
  client/hooks/chat/useGetChatList.tsx
  client/hooks/chat/useGetChatRoomList.tsx
  client/hooks/chat/useGetResetChatAlarm.tsx
  client/hooks/chat/useTranslateTime.tsx
  client/pages/chat/[memberId].tsx
Labels: 🚨 BugFix, ⛲ Feature, FE박성훈

#589 Refactor/things#567
  client/assets/color/color.ts
  client/components/Maincard/Card.tsx
  client/components/Mypage/StudentBookmark.tsx
  client/components/Mypage/StudentClass.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailBasicInfoEditModal.tsx
  client/components/detailComp/DetailExtra.tsx
  client/components/detailComp/DetailExtraModi.tsx
  client/components/detailComp/MobileDetailBasicInfo.tsx
  client/hooks/detail/useGetBasicInfo.tsx
  client/hooks/detail/useGetExtra.tsx
  client/hooks/detail/usePostCurModi.tsx
  client/hooks/detail/usePostExtraModi.tsx
  client/pages/lesson/[id].tsx
  client/pages/shop/[id]/index.tsx
  client/pages/shop/[id]/receipt.tsx
  client/public/images/Kakao.png
  client/public/images/Toss.png
  client/tailwind.config.js
Labels: 🔨 Refactor, FE김상현

#591 feat 마이페이지 학생탭 채팅하기 연결
  client/apis/mypage/deleteAccount.tsx
  client/apis/mypage/deleteApply.tsx
  client/apis/mypage/deleteReview.tsx
  client/apis/mypage/getAllBookmark.tsx
  client/apis/mypage/getCloseClass.tsx
  client/apis/mypage/getMyReview.tsx
  client/apis/mypage/getMyTutor.tsx
  client/apis/mypage/getStudentInfo.tsx
  client/apis/mypage/getTutorInfo.tsx
  client/apis/mypage/postAccept.tsx
  client/apis/mypage/postReview.tsx
  client/components/Detail/DetailButtons.tsx
  client/components/Maincard/Card.tsx
  client/components/Maincard/Pagination.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/FinishedTutor.tsx
  client/components/Mypage/StudentBookmark.tsx
  client/components/Mypage/StudentClass.tsx
  client/components/reuse/container/DetailContentContainer.tsx
  client/pages/mypage/[name].tsx
  client/styles/globals.css
Labels: ⛲ Feature, FE정하늘

#592 feat : 과외후기 수정모달 구현
  client/atoms/main/mainAtom.tsx
  client/components/Detail/DetailButtons.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/ClassList.tsx
  client/components/Mypage/FinishedTutor.tsx
  client/components/Mypage/ReviewEditModal.tsx
  client/components/Mypage/StudentBookmark.tsx
  client/components/Mypage/StudentClass.tsx
  client/components/Mypage/StudentReview.tsx
  client/components/Navbar/Navbar.tsx
  client/components/detailComp/DetailReview.tsx
Labels: ⛲ Feature, FE박성훈

#593 Refactor/things#567
  client/atoms/mypage/myPageAtom.tsx
  client/components/Mypage/EditUserData.tsx
  client/components/Mypage/MypageInfo.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailExtra.tsx
  client/components/detailComp/DetailExtraModi.tsx
  client/components/detailComp/DetailImageModal.tsx
  client/components/detailComp/MobileDetailBasicInfo.tsx
  client/hooks/detail/useGetExtra.tsx
  client/hooks/mypage/usePostMemberModi.tsx
  client/pages/shop/[id]/index.tsx
  client/pages/shop/[id]/receipt.tsx
Labels: 🔨 Refactor, FE김상현

#594 refactor: Authentication 검증용 AuthVO 추가
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/chat/constant/MessageType.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/AlarmController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRegisterController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRoomController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendAlarmMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendAcceptSuggestAlarmEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendRegisterSuggestAlarmEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendRejectSuggestAlarmEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatAlarm.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/ChatRoomUtils.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/MessageType.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CurriculumRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonInfoRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/domain/vo/AuthVO.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/java/com/codueon/boostUp/global/handler/StompHandler.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPatchTest.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
Labels: 🔨 Refactor, BE조경민

#602 refactor: 과외 결제 대기 시 신청 거절 가능하도록 예외 처리 추가
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
Labels: 🔨 Refactor, BE이규리

#601 fix: 실시간채팅 버그 개선
  client/components/chat/ChatComp.tsx
  client/components/chat/ChatContent.tsx
  client/components/chat/ChatListComp.tsx
  client/components/chat/ChatNoticeMessage.tsx
  client/components/filter/LanguageFilter.tsx
  client/components/filter/MobileLanguageFilter.tsx
  client/hooks/chat/socket.tsx
  client/hooks/chat/useTranslateTime.tsx
  client/pages/chat/[memberId].tsx
Labels: 🚨 BugFix, FE박성훈

#600 Feat 마이페이지 거절하기 연결
  client/apis/mypage/postDecline.tsx
  client/components/Mypage/AcceptModal.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/ClassList.tsx
  client/components/Mypage/DeclineModal.tsx
  client/components/Mypage/FinishedTutor.tsx
  client/components/Mypage/StudentBookmark.tsx
  client/components/Mypage/StudentReview.tsx
  client/hooks/mypage/usePostDecline.tsx
Labels: ⛲ Feature, FE정하늘

#603 Refactor/things#567 사이트 리펙토링
  client/apis/auth/deleteLogout.tsx
  client/atoms/auth/authAtom.tsx
  client/components/Header/Header.tsx
  client/components/Maincard/Card.tsx
  client/components/Mypage/MypageInfo.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailExtra.tsx
  client/components/detailComp/DetailImageModal.tsx
  client/hooks/auth/useDeleteLogout.tsx
Labels: 🔨 Refactor, FE김상현

#604 feat: 과외 신청 및 리뷰 알람 기능 추가
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/RedisChat.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/MakeChatRoomEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendAlarmMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/AlarmChatListEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/InitialChatRoomListEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/InitialChatRoomMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/MakeAlarmChatRoomEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/MakeChatRoomEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendAcceptSuggestAlarmEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendAlarmMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendEnterMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendRegisterSuggestAlarmEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendRejectSuggestAlarmEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/vo/SendSuggestMessageEvent.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/querydsl/ChatRoomRepository.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/EventAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/EventMessageService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/SendMessageService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/AlarmMessageUtils.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/AlarmType.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/MessageType.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLessonInfoForAlarm.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberEventService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewDbService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewEventService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestEventService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPostTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
Labels: ⛲ Feature, BE조경민

#606 refactor: getLesson editable 안나오던 부분 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLesson.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
Labels: 🔨 Refactor, BE조경민

#608 refactor: 로그아웃 안되던 부분 수정
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
Labels: 🚨 BugFix, BE조경민

#610 fix: nickname regex 수정
  client/components/chat/ChatNoticeMessage.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/pages/chat/[memberId].tsx
  client/pages/signup.tsx
Labels: 🚨 BugFix, FE박성훈

#611 refactor: 과외 조회 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
Labels: 🚨 BugFix, BE조경민

#613 refactor: LessonInfo 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
Labels: 🚨 BugFix, BE조경민

#615 refactor: 북마크 리팩토링
  server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
Labels: 🔨 Refactor, BE조경민

#616 refactor: 메인페이지 북마크 조회 안되던 부분 수정
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
Labels: 🚨 BugFix, BE조경민

#612 Refactor/things#567 리펙토링
  client/apis/detail/postApply.tsx
  client/apis/detail/postCurModi.tsx
  client/apis/main/postSearch.tsx
  client/apis/main/postWrite.tsx
  client/apis/mypage/getAllBookmark.tsx
  client/apis/mypage/postAccept.tsx
  client/apis/mypage/postDecline.tsx
  client/apis/mypage/postReview.tsx
  client/components/Maincard/Card.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/createModal/Curriculum.tsx
  client/components/detailComp/DetailBasicInfo.tsx
  client/components/detailComp/DetailExtra.tsx
  client/hooks/auth/usePostLogin.tsx
  client/hooks/detail/useGetCurriculum.tsx
  client/hooks/detail/useGetDetailReview.tsx
  client/hooks/detail/useGetExtra.tsx
  client/hooks/main/usePostWrite.tsx
  client/pages/shop/[id]/receipt.tsx
Labels: FE김상현

#620 Feat 후기삭제서버 연결
  client/components/Maincard/Card.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/DeclineModal.tsx
  client/components/Mypage/StudentReview.tsx
  client/components/createModal/BasicInfo.tsx
  client/hooks/detail/useGetBookmark.tsx
  client/hooks/detail/usePostApply.tsx
  client/hooks/main/useGetMainCard.tsx
  client/hooks/mypage/useDeleteFinishedTutor.tsx
  client/hooks/mypage/useGetAllBookmark.tsx
  client/hooks/mypage/useGetCloseClass.tsx
  client/hooks/mypage/useGetMyTutor.tsx
  client/hooks/mypage/useGetStudentInfo.tsx
  client/hooks/mypage/usePostAccept.tsx
  client/hooks/mypage/usePostDecline.tsx
  client/hooks/mypage/usePostReview.tsx
  client/pages/login.tsx
  client/pages/mypage/[name].tsx
Labels: 🖼 HTML&CSS, FE정하늘

#623 fix : 채팅페이지 active상태변화 이슈 해결
  client/apis/mypage/patchReview.tsx
  client/atoms/chat/chatAtom.tsx
  client/atoms/mypage/myPageAtom.tsx
  client/components/Mypage/ReviewEditModal.tsx
  client/components/Mypage/StudentReview.tsx
  client/components/chat/ChatContent.tsx
  client/components/chat/DesktopChatComp.tsx
  client/hooks/mypage/usePatchReview.tsx
  client/pages/index.tsx
  client/pages/mypage/[name].tsx
Labels: 🚨 BugFix, ⛲ Feature, FE박성훈

#624 fix: 채팅서비스 맥북환경에서 메시지 2중전송 이슈 수정
  client/components/chat/ChatComp.tsx
  client/components/chat/DesktopChatComp.tsx
  client/hooks/chat/useGetChatList.tsx
  client/hooks/chat/useGetCreateRoom.tsx
  client/hooks/chat/usePostSendChat.tsx
Labels: 🚨 BugFix, FE박성훈

#626 refactor : updateLesson lessonId 순서 리팩터링
  server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영, BE조경민

#625 feat 북마크 이중 클릭 가능
  client/components/Maincard/Card.tsx
  client/components/Mypage/MypageInfo.tsx
  client/pages/mypage/[name].tsx
Labels: ⛲ Feature, FE정하늘

#627 refactor: suggestController 분리
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPayController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/PaymentController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/TossPayController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/KakaoPayService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/PaymentService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/TossPayService.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPayControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPaymentTest.java
Labels: 🔨 Refactor, BE이규리

#630 feat 소셜로그인버튼
  client/assets/icon/IconKakao.tsx
  client/pages/login.tsx
  client/tailwind.config.js
Labels: ⛲ Feature, FE정하늘

#631 style kakaoIcon 제거
  client/assets/icon/IconKakao.tsx
  client/pages/login.tsx
Labels: ⛲ Feature, FE정하늘

#636 test: Suggest Rest Docs Test 코드 추가
  server/src/asciidoc/index.adoc
  server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPayControllerTest.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPaymentTest.java
Labels: BE이규리, ✅ Test

#637 refactor : 로그인 시 등록한 과외 여부 추가
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
  server/src/main/java/com/codueon/boostUp/domain/member/dto/AuthDto.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
Labels: ⛲ Feature, 👽️ API, 🔨 Refactor, BE주석영

#638 fix : socket 로그 제거 및 전체 페이지 스타일 리팩토링
  client/assets/icon/IconPaper.tsx
  client/assets/icon/IconPlace.tsx
  client/assets/icon/IconRibbon.tsx
  client/components/Maincard/Card.tsx
  client/components/chat/ChatContent.tsx
  client/components/chat/ChatListComp.tsx
  client/components/chat/ChatListContent.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailCurriculum.tsx
  client/components/detailComp/DetailExtra.tsx
  client/components/filter/LanguageFilter.tsx
  client/components/filter/MobileLanguageFilter.tsx
  client/hooks/chat/socket.tsx
  client/pages/index.tsx
  client/pages/login.tsx
  client/public/images/all.png
  client/public/images/allIcon.png
Labels: 🚨 BugFix, 🔨 Refactor, FE박성훈

#641 Refactor/things#567 글작성 값 유지 및 이미지 로직 변경
  client/components/createModal/Curriculum.tsx
  client/components/createModal/ExtraInfo.tsx
  client/components/createModal/WriteModal.tsx
  client/components/detailComp/DetailExtraModi.tsx
  client/package-lock.json
  client/package.json
  client/pages/shop/[id]/receipt.tsx
Labels: FE김상현

#642 style: 상세페이지 참고사진 리사이징
  client/components/Maincard/Card.tsx
  client/components/detailComp/DetailExtra.tsx
Labels: 🖼 HTML&CSS, FE박성훈

#643 feat 페이지네이션 수정
  client/atoms/main/mainAtom.tsx
  client/atoms/mypage/myPageAtom.tsx
  client/components/Maincard/Card.tsx
  client/components/Maincard/Pagination.tsx
  client/components/filter/LanguageFilter.tsx
  client/hooks/board/useGetFilteredBoard.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/api/auth/[...nextauth].ts
Labels: FE정하늘

#646 refactor: edit Lesson 수정
  server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRegisterController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/EventMessageService.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
  server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
  server/src/main/java/com/codueon/boostUp/global/handler/StompHandler.java
  server/src/main/resources/application-prod.yml
  server/src/test/java/com/codueon/boostUp/domain/chat/ChattingFullTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/StompFrameHandlerImpl.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
Labels: 🔨 Refactor, BE조경민

#649 refactor: 프론트 배포 주소 변경에 따른 Origin 수정
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
Labels: 🔨 Refactor, ⚙Setting, BE조경민

#650 Client ssr: CORS 설정 test
  client/next.config.js
Labels: FE김상현

#651 refactor: Suggest 리팩토링 및 코드 정리
  server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/PaymentController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentStatusCheck.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetQuantityCount.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetRefundPayment.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/KakaoPayService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/PaymentService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/service/TossPayService.java
  server/src/main/java/com/codueon/boostUp/domain/suggest/utils/SuggestConstants.java
  server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentTest.java
Labels: 🔨 Refactor, BE이규리

#652 chore: removeImports 삭제 테스트
  client/next.config.js
Labels: FE김상현

#653 fix : filterComp Resizing / set input limit / resetPassword refactoring
  client/components/Detail/ApplyModal.tsx
  client/components/auth/ResetPwEmailAuth.tsx
  client/components/auth/ResetPwSet.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailExtra.tsx
  client/hooks/auth/usePostEmailAuth.tsx
  client/pages/index.tsx
  client/pages/resetPassword.tsx
Labels: 🚨 BugFix, FE박성훈

#654 chore: next config 배포 성공 환경으로 변경
  client/next.config.js
Labels: FE김상현

#657 fix: 로그아웃 버그 수정
  server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
  server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
  server/src/main/java/com/codueon/boostUp/domain/vo/AuthVO.java
Labels: 🚨 BugFix, BE조경민

#660 fix : SecurityFilterChain 수정 1
  server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
Labels: 🔨 Refactor, BE임재민

#661 Refactor/things#567 SEO를 위한 MetaData
  client/apis/auth/deleteLogout.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/reuse/SEO/SeoHead.tsx
  client/next.config.js
  client/pages/_app.tsx
  client/pages/chat/[memberId].tsx
  client/pages/lesson/[id].tsx
  client/pages/login.tsx
  client/pages/mypage/[name].tsx
  client/pages/resetPassword.tsx
  client/pages/shop/[id]/index.tsx
  client/pages/shop/[id]/receipt.tsx
  client/pages/signup.tsx
  client/pages/test.tsx
  client/public/images/favicon-logo.ico
Labels: ⛲ Feature, 🔨 Refactor, FE김상현

#662 SEO MetaData 서버에 적용
  client/apis/auth/deleteLogout.tsx
  client/components/Detail/ApplyModal.tsx
  client/components/auth/ResetPwEmailAuth.tsx
  client/components/auth/ResetPwSet.tsx
  client/components/createModal/BasicInfo.tsx
  client/components/detailComp/DetailExtra.tsx
  client/components/reuse/SEO/SeoHead.tsx
  client/hooks/auth/usePostEmailAuth.tsx
  client/next.config.js
  client/pages/_app.tsx
  client/pages/chat/[memberId].tsx
  client/pages/index.tsx
  client/pages/lesson/[id].tsx
  client/pages/login.tsx
  client/pages/mypage/[name].tsx
  client/pages/resetPassword.tsx
  client/pages/shop/[id]/index.tsx
  client/pages/shop/[id]/receipt.tsx
  client/pages/signup.tsx
  client/pages/test.tsx
  client/public/images/favicon-logo.ico
Labels: ⛲ Feature, FE김상현

#663 Refactor/things#567 이미지 최적화 도메인 설정 및 metadata 위치 변경
  client/next.config.js
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/lesson/[id].tsx
Labels: 🔨 Refactor, FE김상현

#664 이미지 최적화 도메인 설정 및 metadata 위치 변경점 배포 적용
  client/next.config.js
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/lesson/[id].tsx
Labels: 🔨 Refactor, FE김상현

#665 refacor: 불필요 코드 라인 삭제 및 SEO image alt 속성 추가
  client/components/Header/Header.tsx
  client/components/Maincard/Card.tsx
  client/components/detailComp/DetailExtra.tsx
  client/pages/_app.tsx
Labels: 🔨 Refactor, FE김상현

#666 main branch로 이동: refactor-불필요 코드 라인 삭제 및 SEO image alt 속성 추가
  client/components/Header/Header.tsx
  client/components/Maincard/Card.tsx
  client/components/detailComp/DetailExtra.tsx
  client/pages/_app.tsx
Labels: FE김상현

#667 featGoogleOauth
  client/atoms/mypage/myPageAtom.tsx
  client/pages/api/auth/[...nextauth].ts
  client/pages/login.tsx
Labels: ⛲ Feature, FE정하늘

#670 feat: lessonExistence값 반영
  client/components/Header/Header.tsx
  client/hooks/auth/usePostLogin.tsx
Labels: ⛲ Feature, FE박성훈

#671 feat: lessonExistence값 반영 (#670)
  client/components/Header/Header.tsx
  client/hooks/auth/usePostLogin.tsx
Labels: ⛲ Feature, FE박성훈

#673 test: create chatRoom test
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/AlarmController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetAlarmMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatAlarm.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/utils/RedisSubscriber.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
  server/src/main/java/com/codueon/boostUp/global/config/EmbeddedRedisConfig.java
  server/src/main/java/com/codueon/boostUp/global/security/handler/OAuth2SuccessHandler.java
  server/src/test/java/com/codueon/boostUp/domain/chat/ChattingFullTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/chat/SendChatTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/room/CreateChatRoomTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/StompFrameHandlerImpl.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
  server/src/test/java/com/codueon/boostUp/domain/utils/RedisTestContainers.java
Labels: BE조경민, ✅ Test

#675 fix: websocketUtils 수정
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
Labels: 🚨 BugFix, BE조경민

#677 refactor: Lesson 등록 시 글자 수 제한
  server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/entity/Bookmark.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonAddress.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
  server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
Labels: 🔨 Refactor, BE이규리

#678 test: makeChatRoomEventListener 테스트 코드 작성
  server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRoomController.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/MakeChatRoomEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendMessageEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendNewChatAlarmEventListener.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatAlarmService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
  server/src/main/java/com/codueon/boostUp/domain/chat/service/EventMessageService.java
  server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewEventService.java
  server/src/test/java/com/codueon/boostUp/domain/chat/ChatRoomTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/message/controller/SendChatTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/message/event/SendMessageEventListenerTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/room/controller/CreateChatRoomTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/room/event/MakeChatRoomEventListenerTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/ChatMethodUtils.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
  server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
Labels: BE조경민, ✅ Test

#679 [FE] 리팩터링 - 최대 글자 수 제한 및 alert 창 통일
  client/components/Detail/ApplyModal.tsx
  client/components/Detail/DetailButtons.tsx
  client/components/Header/Header.tsx
  client/components/Maincard/Card.tsx
  client/components/Mypage/AcceptModal.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/DeclineModal.tsx
  client/components/Mypage/ReviewModal.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Curriculum.tsx
  client/components/createModal/ExtraInfo.tsx
  client/components/detailComp/DetailCurModi.tsx
  client/components/detailComp/DetailExtraModi.tsx
Labels: 🔨 Refactor, FE김상현

#680 [FE] #679(글자 수 제한 및 alert창) 작업사항 배포환경으로 이동
  client/components/Detail/ApplyModal.tsx
  client/components/Detail/DetailButtons.tsx
  client/components/Header/Header.tsx
  client/components/Maincard/Card.tsx
  client/components/Mypage/AcceptModal.tsx
  client/components/Mypage/ApplicationList.tsx
  client/components/Mypage/DeclineModal.tsx
  client/components/Mypage/ReviewModal.tsx
  client/components/Navbar/Navbar.tsx
  client/components/createModal/Curriculum.tsx
  client/components/createModal/ExtraInfo.tsx
  client/components/detailComp/DetailCurModi.tsx
  client/components/detailComp/DetailExtraModi.tsx
Labels: 🔨 Refactor, FE김상현

#683 feat 회원탈퇴삭제
  client/apis/auth/getGoogleLogin.tsx
  client/components/Mypage/MypageInfo.tsx
  client/hooks/main/useGetMainCard.tsx
  client/pages/login.tsx
Labels: FE정하늘
