Repository boostup-project/boostup-project, pull requests merged in 2023-03, with the labels that each got.

#687 test: chat/chatRoomRepository 테스트 완료
  server/build.gradle
  server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/codueon/boostUp/domain/chat/repository/querydsl/ChatRoomRepository.java
  server/src/main/java/com/codueon/boostUp/global/batch/config/BatchConfig.java
  server/src/test/java/com/codueon/boostUp/BoostUpApplicationTests.java
  server/src/test/java/com/codueon/boostUp/config/JpaQueryFactoryConfig.java
  server/src/test/java/com/codueon/boostUp/domain/chat/WebSocketAuthServiceTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/message/repository/ChatRepositoryTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/room/repository/ChatRoomRepositoryTest.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/DataForChat.java
  server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
Labels: 🚨 BugFix, BE조경민, ✅ Test

#689 docs: client 폴더 리드미 업데이트
  client/README.md
Labels: 📄 Docs, FE김상현, FE정하늘, FE박성훈

#690 refactor: Transfer to SSRDataFetch
  client/components/Maincard/Card.tsx
  client/components/Maincard/Cards.tsx
  client/hooks/auth/useDeleteLogout.tsx
  client/hooks/main/usePostWrite.tsx
  client/pages/index.tsx
Labels: 🔨 Refactor, FE박성훈

#691 refactor: Transfer to SSRDataFetch 작업 건 main 브랜치로 병합요청
  client/components/Maincard/Card.tsx
  client/components/Maincard/Cards.tsx
  client/hooks/auth/useDeleteLogout.tsx
  client/hooks/main/usePostWrite.tsx
  client/pages/index.tsx
Labels: FE박성훈

#692 refactor:transfer to SSRDataFetch
  client/components/Maincard/Card.tsx
  client/pages/index.tsx
Labels: 🔨 Refactor, FE박성훈

#693 refactor: Transfer to SSRDataFetch 작업 건 main 브랜치로 병합요청
  client/components/Maincard/Card.tsx
  client/pages/index.tsx
Labels: 🔨 Refactor, FE박성훈
